<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \Admin\Entity\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'empresa', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'tipo', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'cover', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'social', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'fantasia', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'cnpj', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'ie', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'phone', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'email', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'google', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'facebook', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'twitter', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'street', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'complements', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'number', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'district', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'zip', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'city', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'state', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'country', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'longetude', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'latitude', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'description', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'createdAt', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'empresa', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'tipo', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'cover', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'social', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'fantasia', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'cnpj', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'ie', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'phone', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'email', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'google', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'facebook', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'twitter', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'street', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'complements', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'number', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'district', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'zip', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'city', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'state', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'country', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'longetude', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'latitude', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'description', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'createdAt', '' . "\0" . 'Admin\\Entity\\Empresa' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCover($cover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCover', [$cover]);

        return parent::setCover($cover);
    }

    /**
     * {@inheritDoc}
     */
    public function getCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', []);

        return parent::getCover();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocial($social = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocial', [$social]);

        return parent::setSocial($social);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocial', []);

        return parent::getSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setFantasia($fantasia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFantasia', [$fantasia]);

        return parent::setFantasia($fantasia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFantasia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFantasia', []);

        return parent::getFantasia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', [$cnpj]);

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', []);

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setIe($ie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIe', [$ie]);

        return parent::setIe($ie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIe', []);

        return parent::getIe();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogle($google)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogle', [$google]);

        return parent::setGoogle($google);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogle', []);

        return parent::getGoogle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', [$facebook]);

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', []);

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', [$twitter]);

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', []);

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplements($complements = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplements', [$complements]);

        return parent::setComplements($complements);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplements', []);

        return parent::getComplements();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrict($district = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrict', [$district]);

        return parent::setDistrict($district);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrict', []);

        return parent::getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongetude($longetude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongetude', [$longetude]);

        return parent::setLongetude($longetude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongetude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongetude', []);

        return parent::getLongetude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
