<?php
/**
 * Created by PhpStorm.
 * User: caltj
 * Date: 16/04/2018
 * Time: 22:47
 */

namespace Client\Filter;


use Client\Entity\Client;
use Core\Filter\AbstractFilter;
use Interop\Container\ContainerInterface;
use Zend\InputFilter\InputFilter;

class AuthFilter extends AbstractFilter
{

    /**
     * FilterInterface constructor.
     * @param ContainerInterface $container
     */
    public function __construct( ContainerInterface $container )
    {
        $this->container = $container;
    }

    public function getInputFilter()
    {
        if (!$this->inputFilter):
            $this->inputFilter = new InputFilter();

            $this->inputFilter->add([
                'name' => 'document',
                'required' => true,
                'filters' => $this->filters(),
                'validators' => [
                    $this->RecordExists(Client::class,'document','Documento'),
                    $this->StringLength('Documento'),
                    $this->NotEmpty('Documento'),
                ]
            ]);

            $this->inputFilter->add([
                'name' => 'password',
                'required' => true,
                'filters' => $this->filters(),
                'validators' => [
                    $this->StringLength('Senha'),
                    $this->NotEmpty('Senha'),
                ]
            ]);
        endif;
        return parent::getInputFilter(); // TODO: Change the autogenerated stub
    }

}